name: Secrets and Environment Variables

on:
  schedule:
    - cron: '0 8 * * 5'  # Run every Friday at 8:00 AM (UTC time) i.e 6 pm AEST

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.APP_ID }}

    steps:
      - name: Date & time
        run: date 

      - name: Read a variable
        run: echo "My APP_ID value is ${{ vars.APP_ID }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify the Node.js 18 version
